### ISSUE TITLE
Cannot find calibrated_tf.launch

### ISSUE THREAD

**Issue by dkhanna511** [beltransen/velo2cam_gazebo#11]
Hi, as mentioned in #8, I used  `roslaunch velo2cam_gazebo mono_mono_p1_s1_real.launch` to run the calibration scenario. What is the path where the calibrated file is saved? Also, how can we extract the extrinsic transformation from the calibrated_tf.launch file?

**Comment by beltransen** [comment]
Hi @dkhanna511 . The file is generated in _velo2cam_calibration/launch/_ which is a folder in our[ calibration package](https://github.com/beltransen/velo2cam_calibration) and does not belong to the folder structure of this repository. There you will see the publisher node with the estimated extrinsic parameters in the format (x,y,z, yaw, pitch, roll).
