### ISSUE TITLE
Run 'roslaunch velo2cam_gazebo mono_hdl64_p1_real.launch' error ocurred!

### ISSUE THREAD

**Issue by chongjeelee** [beltransen/velo2cam_gazebo#12]
when run ' roslaunch velo2cam_gazebo mono_hdl64_p1_real.launch ',it ocurred error ,the info below:

![图片](https://user-images.githubusercontent.com/30140969/132663314-35a35a77-df17-40a1-9311-c360654c67be.png)

did you see this error before?if did ,pls help me ,thank you very much!
my ros envir is ros2 melodic ,ubuntu18.04,gazebo9.

**Comment by beltransen** [comment]
Hi @chongjeelee,
it seems to be an error caused by not having placed the models at the location where gazebo looks at (~/.gazebo/models/, as described in the [README](https://github.com/beltransen/velo2cam_gazebo/blob/master/README.md)).

**Comment by chongjeelee** [comment]
it does work,thank you very much! haha

**Comment by chongjeelee** [comment]
> Hi @chongjeelee,
> it seems to be an error caused by not having placed the models at the location where gazebo looks at (~/.gazebo/models/, as described in the [README](https://github.com/beltransen/velo2cam_gazebo/blob/master/README.md)).

it does work,thanks you very much!hah

**Comment by chongjeelee** [comment]
![图片](https://user-images.githubusercontent.com/30140969/132683110-ff9f10c8-5d6c-4bbe-86f9-1d34652abd04.png)
----
i also run again,but no pointcloud generate in rviz,the status is error.
why?maybe some else i need to fix ?

**Comment by beltransen** [comment]
It looks like the point cloud is not displayed because the **fixed frame** set in Rviz does not correspond to the **frame id** of the LiDAR message. Please, try setting it properly or check the error message shown under the **Status** field to see if anything else is happening.

**Comment by chongjeelee** [comment]
> It looks like the point cloud is not displayed because the **fixed frame** set in Rviz does not correspond to the **frame id** of the LiDAR message. Please, try setting it properly or check the error message shown under the **Status** field to see if anything else is happening.

ok ,thank you again!
