### ISSUE TITLE
"‘math’ has not been declared" when catkin_make

### ISSUE THREAD

**Issue by mig29kub** [beltransen/velo2cam_gazebo#13]
I face this issue when build by catkin_make, anyones can help?
 
![image](https://user-images.githubusercontent.com/10691311/133042902-36992dce-aaed-419f-b6cc-b51a6eaf7b8e.png)

**Comment by kartikcode** [comment]
The entire model was probably built in versions before Gazebo 7. With gazebo 9, the following changes need to be made:
`#include <ignition/math/Vector3.hh>`
`ignition::math::Pose3d pose;`
`pose.Pos().X() = .....`

This worked for me. For more details, you can check this [forum](https://answers.ros.org/question/361021/i-try-to-catkin_make-with-gazebo-9-but-i-got-these-errors/).

**Comment by super-scyu** [comment]
how to modify the Gazebo11?
