### ISSUE TITLE
Is it working in Noetic?

### ISSUE THREAD

**Issue by cyhunblr** [beltransen/velo2cam_gazebo#15]
I'm trying to run roslaunch velo2cam_gazebo mono_hdl64_p1_real.launch but doesn't work.

**Comment by beltransen** [comment]
Please, provide details of the error you are experiencing and the versions of the software (e.g. ROS, Gazebo) you are using so that we are able to understand what's going on.

**Comment by Rurinn** [comment]
In noetic with gazebo11 I made some changes to the xacro spawn files in gazebo_models to make model visible in gazebo
for example 
in calibration_whiteqr_spawn.urdf.xacro
add 'xacro:'  in front of 'calibration_whiteqr'

**Comment by XIAONNNN** [comment]
> 在 noetic 中使用 gazebo11 中，我在 gazebo_models 中对 xacro 生成文件进行了一些更改，以使模型在凉亭中可见，例如在 calibration_whiteqr_spawn.urdf.xacro 中添加 'xacro：“在”calibration_whiteqr“前面添加 'xacro： '

it works,thanks
