### ISSUE TITLE
The monocular camera does not recognize the QR

### ISSUE THREAD

**Issue by Jiwen1ei** [beltransen/velo2cam_gazebo#18]
Thank you so much for sharing!
When I use velo2cam_gazebo it appears that the monocular camera does not recognize the QR.
How can I solve this problem?
![2023-09-16 18-27-30 的屏幕截图](https://github.com/beltransen/velo2cam_gazebo/assets/129354170/9f965a8d-d550-4708-8c23-885f9240f56c)

**Comment by wroomhers** [comment]
did you solve it
