### ISSUE TITLE
How to record simulated data

### ISSUE THREAD

**Issue by BorisLerouxFox** [beltransen/velo2cam_gazebo#6]
Dear everyone,
Impressive works, thanks for sharing.
I'm a newbie at Gazebo and ROS and I don't know how to record simulated data in readable files like LAS/ASCII point cloud for Velodyne and JPG/TIF images for the stereo camera.
I have already try :
`rostopic echo /velodyne_points > test.txt`
and also :
`rosbag record -O subset /velodyne_points`
But, both of this files are not easily readable for me, so can you explain me how to export it in the right format ?
Please let me know
Chears
Boris

**Comment by beltransen** [comment]
Hi Boris,
I think there is no straightforward method to record ROS messages in the format you want. The easiest way should be to create a ROS node that listens to the LiDAR and camera messages and save them in the desired file format. 
[Here](http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28c%2B%2B%29) you can find the ROS tutorial to write a C++ subscriber, and [here](http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28python%29) you can find the Python version.

Hope this helps,
Jorge

**Comment by BorisLerouxFox** [comment]
I have found a way to do it,
Just record the /velodyne_point topic in a bag file :
`rosbag record -O velodyne /velodyne_points`
Then convert the bag PointCloud2 message to PCL *.pcd format :
`rosrun pcl_ros bag_to_pcd velodyne.bag /velodyne_points ./pointscloud`
Then convert binary *.pcd file into ASCII *.pcd files :
`pcl_conver_ascii_binary *.pcd *_ascii.pcd ascii`
In attachment, you will find a snapshot of the pointcloud opened in CloudCompare
![test_calib](https://user-images.githubusercontent.com/30866631/42318916-be727152-8050-11e8-9eda-72b9893a7e71.JPG)

I will also try your solution, thanks for your help.
Best regards
Boris

**Comment by beltransen** [comment]
Glad to hear that you found a solution. Thanks for sharing your approach.
I'll close the issue then.

Regards,
Jorge
