### ISSUE TITLE
Simulation Models

### ISSUE THREAD

**Issue by DChaddy** [beltransen/velo2cam_gazebo#7]
When running the simulation it tries to download the models from gazebosim.org/models which no longer exists so it is unable to find them. This results in the objects being boxes instead of the velodyne and calibration image.

**Comment by cguindel** [comment]
Hi @DChaddy,

Did you solve the problem? Can you provide some hints on how to deal with it, for future reference?

Thank you.

**Comment by DChaddy** [comment]
To fix this I make the ~/.gazebo/models directory and placed the models from gazebo into this. This allowed me to test the simulation and the models did not have to be downloaded because they were already in the correct place.

**Comment by cguindel** [comment]
Thank you very much! We'll look at it to check if the problem is on our side.
