### ISSUE TITLE
GPU Acceleration

### ISSUE THREAD

**Issue by ardabbour** [beltransen/velo2cam_gazebo#9]
The Velodyne models here do not use GPU acceleration. Using a sensor of type `gpu_ray` instead of `ray` and a plugin filename of `libgazebo_ros_velodyne_gpu_laser` instead of `libgazebo_ros_velodyne_laser` allows for much faster performance.

This can be made parametric to support only-CPU setups as well if the models are made into xacro format, as in the [velodyne_description](https://bitbucket.org/DataspeedInc/velodyne_simulator/) package. For instance, here is the [HDL-32E xacro description](https://bitbucket.org/DataspeedInc/velodyne_simulator/src/master/velodyne_description/urdf/HDL-32E.urdf.xacro).

**Comment by beltransen** [comment]
Thanks for the information @ardabbour. I have checked this package and it seems to be working badly for some gazebo versions. Therefore, until a stable behaviour is provided for most popular gazebo releases, I'm sorry to say that we will have to stay with the CPU model. 

Here below you can find what I get when running the example scenario in ROS Kinetic and Gazebo 7.0.0 (the one shipped with ROS Kinetic). 

CPU version:
![Screenshot_20200520_111441](https://user-images.githubusercontent.com/2643936/82463916-6e4ea180-9a8b-11ea-9d4e-cd13d1fa74be.png)

GPU version:
![Screenshot_20200520_110735](https://user-images.githubusercontent.com/2643936/82463945-77d80980-9a8b-11ea-8743-7bee33ca84fd.png)
